# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    key            = "./terraform.tfstate"
    region         = "us-east-1"
    bucket         = "asana-sgtm-terraform-state-bucket"
    dynamodb_table = "sgtm_terraform_state_lock"
  }
}
