version: 2.1

orbs:
  python: circleci/python@1.4.0

commands:
  setup:
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pip-dependency-file: requirements-dev.txt

jobs:
  black:
    executor: python/default
    steps:
      - setup
      - run:
          command: black --check src test scripts

  mypy:
    executor: python/default
    steps:
      - setup
      - run:
          command: mypy src test scripts

  test:
    executor: python/default
    steps:
      - setup
      - run:
          command: python3 -m unittest discover
          name: Test
          environment:
            AWS_DEFAULT_REGION: us-east-1

workflows:
  main:
    jobs:
      - test
      - black:
          filters:
            branches:
              ignore: master
      - mypy:
          filters:
            branches:
              ignore: master
