version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - run: pip install -r requirements-dev.txt
      - python/save-cache
      - run:
          command: python3 -m unittest discover
          name: Test

workflows:
  main:
    jobs:
      - test
