version: 2.1

orbs:
  python: circleci/python@1.4.0

commands:
  setup:
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
          args: --dev

jobs:
  black:
    docker:
      - image: circleci/python:3.9
    steps:
      - setup
      - run:
          command: pipenv run black --check src test scripts

  mypy:
    docker:
      - image: circleci/python:3.9
    steps:
      - setup
      - run:
          command: pipenv run mypy src test scripts

  test:
    docker:
      - image: circleci/python:3.9
    steps:
      - setup
      - run:
          command: pipenv run python3 -m unittest discover
          name: Test
          environment:
            AWS_DEFAULT_REGION: us-east-1
            GITHUB_API_KEY: test-key

workflows:
  main:
    jobs:
      - test
      - black:
          filters:
            branches:
              ignore: master
      - mypy:
          filters:
            branches:
              ignore: master
